version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.5-4
    environment:
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud_db
    volumes:
    - /srv/docker/nextcloud/postgresql:/var/lib/postgresql

  nextcloud:
    restart: always
    image: sameersbn/nextcloud:9.0.55
    command: app:nextcloud
    environment:
    - DEBUG=false
    - TZ=Asia/Kolkata

    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud_db

    - NEXTCLOUD_URL=http://cloud.example.com:10080

    - NEXTCLOUD_ADMIN_USER=
    - NEXTCLOUD_ADMIN_PASSWORD=

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - /srv/docker/nextcloud/nextcloud:/var/lib/nextcloud

  nginx:
    restart: always
    image: sameersbn/nextcloud:9.0.55
    command: app:nginx
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud
    ports:
    - "10080:80"
